name: Edit request
description: Request for changes to the Atlas data 
labels: ["atlas data: request"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the changes
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: true