name: Validate JSON files
on:
  push:
    paths:
      - web/atlas.json
      - data/patches/*.json
  pull_request:
    paths:
      - web/atlas.json
      - data/patches/*.json
jobs:
  validate:
    name: Validate
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tools/ci/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Validate
        run: |
          pip3 install -r tools/ci/requirements.txt
          python3 tools/ci/validate_json.py web/atlas.json tools/schema/atlas.json
          python3 tools/ci/validate_json.py data/patches tools/schema/patch.json  